from unittest_reinvent.running_modes.local_logger_tests.test_sampling_invalid_smiles import TestSamplingInvalidSmiles
from unittest_reinvent.running_modes.local_logger_tests.test_transfer_logger import TestTransferLogger

