from unittest_reinvent.running_modes.reinforcement_tests.test_reinforce_tanimoto_similarity import \
    TestReinforceTanimotoSimilarity
from unittest_reinvent.running_modes.reinforcement_tests.test_margin_guard import MarginGuardStoreTest
from unittest_reinvent.running_modes.reinforcement_tests.test_margin_guard_increase_sigma import \
    MarginGuardIncreaseSigmaTest
from unittest_reinvent.running_modes.reinforcement_tests.test_margin_guard_adjust_guard import \
    MarginGuardAdjustGuardTest
from unittest_reinvent.running_modes.reinforcement_tests.test_margin_guard_adjust_guard_on_empty import \
    MarginGuardAdjustGuardOnEmptyTest
from unittest_reinvent.running_modes.reinforcement_tests.test_margin_guard_threshold import MarginGuardThresholdTest
from unittest_reinvent.running_modes.reinforcement_tests.test_margin_guard_mean_stats import \
    MarginGuardMeanStatsTest
from unittest_reinvent.running_modes.reinforcement_tests.test_link_invent_reinforcement_learning_runner import \
    TestLinkInventReinforcementLearningRunner
