#from communication.score_summary import ScoreSummary
#from communication.scoring_function_parameters import ScoringFuncionParameters
#from communication.configuration import ConfigurationEnvelope
#from communication.manager import Manager