from running_modes.configurations.create_model.create_model_configuration import CreateModelConfiguration
from running_modes.configurations.create_model.link_invent_create_model_configuration import \
    LinkInventCreateModelConfiguration
