from unittest_reinvent.running_modes.inception_tests.test_add import TestInceptionModelAdd
from unittest_reinvent.running_modes.inception_tests.test_add_jaccard_distance import TestInceptionAddJaccardDistance
from unittest_reinvent.running_modes.inception_tests.test_eval_add_tanimoto import TestInceptionEvalAddTanimoto
from unittest_reinvent.running_modes.inception_tests.test_empty_add import TestInceptionEmptyAddSmiles
from unittest_reinvent.running_modes.inception_tests.test_empty_eval_add_tanimoto import \
    TestInceptionEmptyEvalAddTanimoto
